packages:
  - "packages/*"
  - "apps/*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: 0.2.2
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
